@DeliveryApi_HostAddress = http://localhost:5230
###Ver todos los productos
GET {{DeliveryApi_HostAddress}}/api/products
Accept: application/json

###Listar unico producto
GET {{DeliveryApi_HostAddress}}/api/products/2
Accept: application/json

###Crear Producto
POST {{DeliveryApi_HostAddress}}/api/products
Content-Type: application/json

{
    "Name":"Coca-cola",
    "Description":"Coca-cola 500ml",
    "Category":"Bebida",
    "Price":7,
    "IsAvailable":true
}

###Actualizar Producto
PUT {{DeliveryApi_HostAddress}}/api/products/2
Content-Type: application/json

{
    "Name":"Cerveza",
    "Description":"Cerveza litro",
    "Category":"Cerveza",
    "Price":25,
    "IsAvailable":true
}

###Eliminar Producto
DELETE {{DeliveryApi_HostAddress}}/api/products/4
Accept: application/json
